# Generated by Django 4.2.7 on 2023-11-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Lastname',
            new_name='lastname',
        ),
    ]
