# Generated by Django 4.2.7 on 2023-11-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0002_rename_firstname_users_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, null=True)),
                ('qr_value', models.TextField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_url_id', to='machineapp.users')),
            ],
        ),
    ]
