# Generated by Django 4.2.7 on 2023-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0003_urldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldetails',
            name='visited_count',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
